<#
Exports all application data (users, projects, issues, kanban, etc.) from the running
`db` service into a plain-SQL file that `import-data.ps1` can replay on another machine.

Data-only: schema comes from Alembic migrations (already run by the `api-migrate` service
on `docker compose up`), not from this dump. `roles`/`user_roles` are handled specially -
`roles.id` is a random UUID regenerated by the seed migrations on every fresh install, so
raw role_id values from this database would not match a fresh one. Instead, `user_roles`
grants are re-derived by role NAME at restore time, after the target's own migrations have
seeded its own `roles` rows.

Must be run from the repo root (where docker-compose.yml lives) with the stack up
(`docker compose up -d`).
#>
param(
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) "EngineOps-data-backup.sql")
)
$ErrorActionPreference = "Stop"

Write-Host "Dumping application data from the db service..."
$dump = docker compose exec -T db pg_dump -U ops_platform -d ops_platform --data-only --disable-triggers `
    --exclude-table=alembic_version --exclude-table=roles --exclude-table=user_roles
if ($LASTEXITCODE -ne 0) { throw "pg_dump failed (exit $LASTEXITCODE)" }

$rows = docker compose exec -T db psql -U ops_platform -d ops_platform -t -A -F"," `
    -c "SELECT ur.user_id, r.name FROM user_roles ur JOIN roles r ON r.id = ur.role_id;"
if ($LASTEXITCODE -ne 0) { throw "user_roles query failed (exit $LASTEXITCODE)" }

$remapLines = New-Object System.Collections.Generic.List[string]
$remapLines.Add("")
$remapLines.Add("-- user_roles restored by role NAME, not raw id: roles.id is regenerated")
$remapLines.Add("-- randomly by the seed migrations on every fresh install, so this source")
$remapLines.Add("-- database's role_id values would not match the target's. Schema-qualified")
$remapLines.Add("-- (public.) because pg_dump sets search_path='' above for restore safety.")

$values = [System.Collections.Generic.List[string]]::new()
foreach ($line in $rows) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    $parts = $line.Split(",")
    $values.Add("  ('$($parts[0])', '$($parts[1])')")
}

if ($values.Count -gt 0) {
    $remapLines.Add("INSERT INTO public.user_roles (user_id, role_id)")
    $remapLines.Add("SELECT v.user_id::uuid, r.id FROM (")
    $remapLines.Add("VALUES")
    $remapLines.Add(($values -join ",`n"))
    $remapLines.Add(") AS v(user_id, role_name)")
    $remapLines.Add("JOIN public.roles r ON r.name = v.role_name")
    $remapLines.Add("ON CONFLICT DO NOTHING;")
}

# Written with .NET's WriteAllLines (no BOM) rather than Out-File/Set-Content - Windows
# PowerShell 5.1 defaults those to UTF-8 WITH BOM, and a BOM at the top of the file breaks
# psql's SQL parsing on restore.
$allLines = @($dump) + $remapLines
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($OutFile, $allLines, $utf8NoBom)

Write-Host "Data backup written to $OutFile"
